version: '3.8'

services:
  

  # redis with persistent data storage
  redis:
    image: "redis:latest"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: