version: '3.8'

services:
  pokebattle:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./pokebattle:/app/pokebattle
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # redis with persistent data storage
  redis:
    image: "redis:latest"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: